# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download repository
      uses: actions/checkout@v3.5.0
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
      
    - name: Cache Dockerlayers
      uses: actions/cache@v3.3.1
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Ubuntu base image
      uses: docker/build-push-action@v4
      with:
        context: ./base/
        file: ./base/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-base:21.10
        cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-base-cache:21.10
        cache-to: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-base-cache:21.10
    - name: Build and push Ubuntu Java image
      uses: docker/build-push-action@v4
      with:
        context: ./java/
        file:  ./java/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-java:21.10
        cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-java-cache:21.10
        cache-to: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-java-cache:21.10
    - name: Build and push Ubuntu Go image
      uses: docker/build-push-action@v4
      with:
        context: ./go/
        file:  ./go/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-go:21.10
        cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-go-cache:21.10
        cache-to: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-go-cache:21.10